version: "3.5"

services:
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  hasura:
    image: hasura/graphql-engine:v1.2.1.cli-migrations
    ports:
      - "8090:8080"
    depends_on:
      - "postgres"
    restart: on-failure
    volumes:
      - ./hasura-migrations:/hasura-migrations
    environment:
      - HASURA_GRAPHQL_ADMIN_SECRET=123
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:password@postgres:5432/test
      - HASURA_GRAPHQL_ENABLE_ALLOWLIST=true
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, query-log
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=public